# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example-app

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install Poetry Action
      uses: snok/install-poetry@v1.3.3
      with:
        virtualenvs-in-project: true
        
    - name: Load cache
      id: cached-venv
      uses: actions/cache@v3
      with:
        path: .venv
        key: ${{ runner.os }}-venv
      
    - name: Install dependencies
      if: steps.cached-venv.outputs.cache-hit != 'true'
      run: poetry install --no-interaction --no-root
      

  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example-app
    needs: build
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      
      - name: Lint
        run: poetry run task lint
        
      - name: Formatter
        run: poetry run task formatter
        
      - name: Security
        run: poetry run task security
        
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./example-app
    needs: build
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      
      - name: Unit tests
        run: poetry run task test
